CREATE TABLE team_stats (
  id INT(10)   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  team_name    VARCHAR(50) NOT NULL,
  source_team_name VARCHAR(50) NOT NULL,
  season_start_year INT(4) NOT NULL,
  season_end_year INT(4) NOT NULL,
  assist_per_turnover_ratio DOUBLE(10, 3),
  assist_per_turnover_ratio_rank INT(4),
  assists_per_fgm DOUBLE(10, 3),
  assists_per_fgm_rank INT(4),
  assists_per_game DOUBLE(10, 3),
  assists_per_game_rank INT(4),
  assists_per_possession DOUBLE(10, 3),
  assists_per_possession_rank INT(4),
  average_1st_half_margin DOUBLE(10, 3),
  average_1st_half_margin_rank INT(4),
  average_2nd_half_margin DOUBLE(10, 3),
  average_2nd_half_margin_rank INT(4),
  average_overtime_margin DOUBLE(10, 3),
  average_overtime_margin_rank INT(4),
  average_scoring_margin DOUBLE(10, 3),
  average_scoring_margin_rank INT(4),
  block_pct DOUBLE(10, 3),
  block_pct_rank INT(4),
  blocks_per_game DOUBLE(10, 3),
  blocks_per_game_rank INT(4),
  defensive_efficiency DOUBLE(10, 3),
  defensive_efficiency_rank INT(4),
  defensive_rebounding_pct DOUBLE(10, 3),
  defensive_rebounding_pct_rank INT(4),
  defensive_rebounds_per_game DOUBLE(10, 3),
  defensive_rebounds_per_game_rank INT(4),
  effective_field_goal_pct DOUBLE(10, 3),
  effective_field_goal_pct_rank INT(4),
  effective_possession_ratio DOUBLE(10, 3),
  effective_possession_ratio_rank INT(4),
  extra_chances_per_game DOUBLE(10, 3),
  extra_chances_per_game_rank INT(4),
  field_goals_attempted_per_game DOUBLE(10, 3),
  field_goals_attempted_per_game_rank INT(4),
  field_goals_made_per_game DOUBLE(10, 3),
  field_goals_made_per_game_rank INT(4),
  floor_percentage DOUBLE(10, 3),
  floor_percentage_rank INT(4),
  free_throw_pct DOUBLE(10, 3),
  free_throw_pct_rank INT(4),
  free_throw_rate DOUBLE(10, 3),
  free_throw_rate_rank INT(4),
  free_throws_attempted_per_game DOUBLE(10, 3),
  free_throws_attempted_per_game_rank INT(4),
  free_throws_made_per_game DOUBLE(10, 3),
  free_throws_made_per_game_rank INT(4),
  fta_per_fga DOUBLE(10, 3),
  fta_per_fga_rank INT(4),
  ftm_per_100_possessions DOUBLE(10, 3),
  ftm_per_100_possessions_rank INT(4),
  games_played DOUBLE(10, 3),
  games_played_rank INT(4),
  non_blocked_2_pt_pct DOUBLE(10, 3),
  non_blocked_2_pt_pct_rank INT(4),
  offensive_efficiency DOUBLE(10, 3),
  offensive_efficiency_rank INT(4),
  offensive_rebounding_pct DOUBLE(10, 3),
  offensive_rebounding_pct_rank INT(4),
  offensive_rebounds_per_game DOUBLE(10, 3),
  offensive_rebounds_per_game_rank INT(4),
  opponent_1st_half_points_per_game DOUBLE(10, 3),
  opponent_1st_half_points_per_game_rank INT(4),
  opponent_2nd_half_points_per_game DOUBLE(10, 3),
  opponent_2nd_half_points_per_game_rank INT(4),
  opponent_assist_per_turnover_ratio DOUBLE(10, 3),
  opponent_assist_per_turnover_ratio_rank INT(4),
  opponent_assists_per_fgm DOUBLE(10, 3),
  opponent_assists_per_fgm_rank INT(4),
  opponent_assists_per_game DOUBLE(10, 3),
  opponent_assists_per_game_rank INT(4),
  opponent_assists_per_possession DOUBLE(10, 3),
  opponent_assists_per_possession_rank INT(4),
  opponent_average_scoring_margin DOUBLE(10, 3),
  opponent_average_scoring_margin_rank INT(4),
  opponent_block_pct DOUBLE(10, 3),
  opponent_block_pct_rank INT(4),
  opponent_blocks_per_game DOUBLE(10, 3),
  opponent_blocks_per_game_rank INT(4),
  opponent_defensive_rebounding_pct DOUBLE(10, 3),
  opponent_defensive_rebounding_pct_rank INT(4),
  opponent_defensive_rebounds_per_game DOUBLE(10, 3),
  opponent_defensive_rebounds_per_game_rank INT(4),
  opponent_effective_field_goal_pct DOUBLE(10, 3),
  opponent_effective_field_goal_pct_rank INT(4),
  opponent_effective_possession_ratio DOUBLE(10, 3),
  opponent_effective_possession_ratio_rank INT(4),
  opponent_field_goals_attempted_per_game DOUBLE(10, 3),
  opponent_field_goals_attempted_per_game_rank INT(4),
  opponent_field_goals_made_per_game DOUBLE(10, 3),
  opponent_field_goals_made_per_game_rank INT(4),
  opponent_floor_percentage DOUBLE(10, 3),
  opponent_floor_percentage_rank INT(4),
  opponent_free_throw_pct DOUBLE(10, 3),
  opponent_free_throw_pct_rank INT(4),
  opponent_free_throw_rate DOUBLE(10, 3),
  opponent_free_throw_rate_rank INT(4),
  opponent_free_throws_attempted_per_game DOUBLE(10, 3),
  opponent_free_throws_attempted_per_game_rank INT(4),
  opponent_free_throws_made_per_game DOUBLE(10, 3),
  opponent_free_throws_made_per_game_rank INT(4),
  opponent_fta_per_fga DOUBLE(10, 3),
  opponent_fta_per_fga_rank INT(4),
  opponent_ftm_per_100_possessions DOUBLE(10, 3),
  opponent_ftm_per_100_possessions_rank INT(4),
  opponent_non_blocked_2_pt_pct DOUBLE(10, 3),
  opponent_non_blocked_2_pt_pct_rank INT(4),
  opponent_offensive_rebounding_pct DOUBLE(10, 3),
  opponent_offensive_rebounding_pct_rank INT(4),
  opponent_offensive_rebounds_per_game DOUBLE(10, 3),
  opponent_offensive_rebounds_per_game_rank INT(4),
  opponent_overtime_points_per_game DOUBLE(10, 3),
  opponent_overtime_points_per_game_rank INT(4),
  opponent_percent_of_points_from_2_pointers DOUBLE(10, 3),
  opponent_percent_of_points_from_2_pointers_rank INT(4),
  opponent_percent_of_points_from_3_pointers DOUBLE(10, 3),
  opponent_percent_of_points_from_3_pointers_rank INT(4),
  opponent_percent_of_points_from_free_throws DOUBLE(10, 3),
  opponent_percent_of_points_from_free_throws_rank INT(4),
  opponent_personal_foul_pct DOUBLE(10, 3),
  opponent_personal_foul_pct_rank INT(4),
  opponent_personal_fouls_per_game DOUBLE(10, 3),
  opponent_personal_fouls_per_game_rank INT(4),
  opponent_personal_fouls_per_possession DOUBLE(10, 3),
  opponent_personal_fouls_per_possession_rank INT(4),
  opponent_points_from_2_pointers DOUBLE(10, 3),
  opponent_points_from_2_pointers_rank INT(4),
  opponent_points_from_3_pointers DOUBLE(10, 3),
  opponent_points_from_3_pointers_rank INT(4),
  opponent_points_per_game DOUBLE(10, 3),
  opponent_points_per_game_rank INT(4),
  opponent_shooting_pct DOUBLE(10, 3),
  opponent_shooting_pct_rank INT(4),
  opponent_steal_pct DOUBLE(10, 3),
  opponent_steal_pct_rank INT(4),
  opponent_steals_per_game DOUBLE(10, 3),
  opponent_steals_per_game_rank INT(4),
  opponent_steals_perpossession DOUBLE(10, 3),
  opponent_steals_perpossession_rank INT(4),
  opponent_team_rebounds_per_game DOUBLE(10, 3),
  opponent_team_rebounds_per_game_rank INT(4),
  opponent_three_point_pct DOUBLE(10, 3),
  opponent_three_point_pct_rank INT(4),
  opponent_three_point_rate DOUBLE(10, 3),
  opponent_three_point_rate_rank INT(4),
  opponent_three_pointers_attempted_per_game DOUBLE(10, 3),
  opponent_three_pointers_attempted_per_game_rank INT(4),
  opponent_three_pointers_made_per_game DOUBLE(10, 3),
  opponent_three_pointers_made_per_game_rank INT(4),
  opponent_total_rebounds_per_game DOUBLE(10, 3),
  opponent_total_rebounds_per_game_rank INT(4),
  opponent_true_shooting_percentage DOUBLE(10, 3),
  opponent_true_shooting_percentage_rank INT(4),
  opponent_turnover_pct DOUBLE(10, 3),
  opponent_turnover_pct_rank INT(4),
  opponent_turnovers_per_game DOUBLE(10, 3),
  opponent_turnovers_per_game_rank INT(4),
  opponent_turnovers_per_possession DOUBLE(10, 3),
  opponent_turnovers_per_possession_rank INT(4),
  opponent_two_point_pct DOUBLE(10, 3),
  opponent_two_point_pct_rank INT(4),
  opponent_two_point_rate DOUBLE(10, 3),
  opponent_two_point_rate_rank INT(4),
  opponent_win_pct_all_games DOUBLE(10, 3),
  opponent_win_pct_all_games_rank INT(4),
  opponent_win_pct_close_games DOUBLE(10, 3),
  opponent_win_pct_close_games_rank INT(4),
  overtime_points_per_game DOUBLE(10, 3),
  overtime_points_per_game_rank INT(4),
  percent_of_points_from_2_pointers DOUBLE(10, 3),
  percent_of_points_from_2_pointers_rank INT(4),
  percent_of_points_from_3_pointers DOUBLE(10, 3),
  percent_of_points_from_3_pointers_rank INT(4),
  percent_of_points_from_free_throws DOUBLE(10, 3),
  percent_of_points_from_free_throws_rank INT(4),
  personal_foul_pct DOUBLE(10, 3),
  personal_foul_pct_rank INT(4),
  personal_fouls_per_game DOUBLE(10, 3),
  personal_fouls_per_game_rank INT(4),
  personal_fouls_per_possession DOUBLE(10, 3),
  personal_fouls_per_possession_rank INT(4),
  points_from_2_pointers DOUBLE(10, 3),
  points_from_2_pointers_rank INT(4),
  points_from_3_pointers DOUBLE(10, 3),
  points_from_3_pointers_rank INT(4),
  points_per_game DOUBLE(10, 3),
  points_per_game_rank INT(4),
  possessions_per_game DOUBLE(10, 3),
  possessions_per_game_rank INT(4),
  shooting_pct DOUBLE(10, 3),
  shooting_pct_rank INT(4),
  steal_pct DOUBLE(10, 3),
  steal_pct_rank INT(4),
  steals_per_game DOUBLE(10, 3),
  steals_per_game_rank INT(4),
  steals_perpossession DOUBLE(10, 3),
  steals_perpossession_rank INT(4),
  team_rebounds_per_game DOUBLE(10, 3),
  team_rebounds_per_game_rank INT(4),
  three_point_pct DOUBLE(10, 3),
  three_point_pct_rank INT(4),
  three_point_rate DOUBLE(10, 3),
  three_point_rate_rank INT(4),
  three_pointers_attempted_per_game DOUBLE(10, 3),
  three_pointers_attempted_per_game_rank INT(4),
  three_pointers_made_per_game DOUBLE(10, 3),
  three_pointers_made_per_game_rank INT(4),
  total_rebounding_percentage DOUBLE(10, 3),
  total_rebounding_percentage_rank INT(4),
  total_rebounds_per_game DOUBLE(10, 3),
  total_rebounds_per_game_rank INT(4),
  true_shooting_percentage DOUBLE(10, 3),
  true_shooting_percentage_rank INT(4),
  turnover_pct DOUBLE(10, 3),
  turnover_pct_rank INT(4),
  turnovers_per_game DOUBLE(10, 3),
  turnovers_per_game_rank INT(4),
  turnovers_per_possession DOUBLE(10, 3),
  turnovers_per_possession_rank INT(4),
  two_point_pct DOUBLE(10, 3),
  two_point_pct_rank INT(4),
  two_point_rate DOUBLE(10, 3),
  two_point_rate_rank INT(4),
  win_pct_all_games DOUBLE(10, 3),
  win_pct_all_games_rank INT(4),
  win_pct_close_games DOUBLE(10, 3),
  win_pct_close_games_rank INT(4),
  ncaa_round_64  INT(1) DEFAULT 0,
  ncaa_round_32  INT(1) DEFAULT 0,
  ncaa_sweet_16  INT(1) DEFAULT 0,
  ncaa_elite_8  INT(1) DEFAULT 0,
  ncaa_final_4  INT(1) DEFAULT 0,
  ncaa_championship_game  INT(1) DEFAULT 0,
  ncaa_champion  INT(1) DEFAULT 0,
  last_update_date DATETIME DEFAULT CURRENT_TIMESTAMP
);